### ISSUE TITLE
"keep info private"  = can be seen in spreadsheet / raw data

### ISSUE THREAD

**Issue by charlw** [bufferapp/diversity-dashboard#15]
Since you are publicly exposing the link to your Google Sheet in the source-code, perhaps you should consider removing the 13 rows where people have asked to keep their information private? Also, this data is in the raw data section of http://diversity.buffer.com too.

Row 422 / timestamp 7/1/2015 20:20:47 contains 'other thoughts' which could easily be used to trace the person. There's enough background information there.

I like to see that Buffer is trying, but this along with the 'self described' issue (#7) is making this attempt at diversity rather unpleasant.

**Comment by charlw** [comment]
Thinking about it, perhaps 'opt in' means don't share name and more 'personal' details... but there is no reason for Buffer to reveal that information anyway, so I doubt it.

**Comment by michael-erasmus** [comment]
@charlw thanks so much for bringing this to our attention, and super sorry for the delay in answering! This is definitely a bug that slipped in, basically we changed the text value of the opt out field and thus those weren't filtered out correctly in the 'Raw data' tab of the dashboard. 

Here is the fix with the commit: https://github.com/bufferapp/diversity-dashboard/commit/cfb2f90b7fae67359214a51b9653656cd48ddedc

And it's also deployed on the live site, please let us know if you spot anything funky though!

The trickier part is how to handle the data that's in the public spreadsheet. Ideally we wanted to have this data available for us to see, but not compromise the privacy of respondents. We've sparked of a conversation with the team to figure this out, hopefully we'll have a better solution to this soon!

**Comment by charlw** [comment]
Ah, I see! Would be interesting to hear of any solutions you may come up with to dealing with the spreadsheet problem.
