### ISSUE TITLE
More nuanced gender selection

### ISSUE THREAD

**Issue by scottkellum** [bufferapp/diversity-dashboard#7]
Currently it looks like people have the option to choose `man`, `woman`, _or_ `trans` but most trans people identify as either `man` or `woman`. The nuances here make it very difficult for check boxes to work which is why [many websites are moving towards a text field](http://www.theverge.com/2015/2/26/8116527/facebook-custom-gender-options) for identification instead of check boxes. Note that there are many many many more gender identities and most of them are not mutually exclusive.

Ultimately it’s nice to have this data but maybe look into ways of collecting it that allow for nuance? Maybe work with trans and genderqueer communities and offer up an input field to refine what is here and parse out that data in a way that won’t make people uncomfortable if they don’t fit into the buckets provided?

**Comment by michael-erasmus** [comment]
Thanks for the great issue @scottkellum, this is such an enlightening discussion! We decided to remove the trans category, and leave the self-described field for people who feel they don't fit into the `man` or `woman` gender identity.

Here is the commit:

https://github.com/bufferapp/diversity-dashboard/commit/3cf8c6e094533838847c5ef6cba717b998ce4511

Where still learning a lot here, and I really appreciate your feedback!

**Comment by scottkellum** [comment]
I think this is a half-step in the right direction but the suggestion in that thread to add _“Prefers not to answer”_ sounds good. Again, talking with someone who is not cisgender might be a good idea.

**Comment by charlw** [comment]
Although this has been closed for a while I've seen this discussed substantially today. "Self described" is a horrible term and invalidates peoples' identities. Please - talk to some non cisgender people as @scottkellum suggested.

**Comment by jamesdaniels** [comment]
Throwing in with @scottkellum @charlw here :+1: Seeing "self described" on the dashboard is super gross.

**Comment by scottkellum** [comment]
I think this issue highlights why team diversity is so important. Not having anyone on the team who understands these issues makes it incredibly difficult to design products that accommodate people with these issues.

**Comment by scottkellum** [comment]
@michael-erasmus curious what plans there are to fix this?

**Comment by michael-erasmus** [comment]
Hey @charlw, @jamesdaniels and @scottkellum so sorry for being so quiet on this front, the whole Buffer team was in Iceland for a while and I failed to keep up with my GH notifications! My dearest apologies! 

I really appreciate all your great feedback, I'll be the first admit that I'm not an expert at this domain but I love learning more and this such an educating conversation! 

I feel that is a really important to get this right, but I'm also sure that we might make lot's of mistakes along the way (like we have already).

I'm really curious about how you see us tackling this one? I have an intuition that giving people a free text field would be great, but I'm not sure how that fits in with the overall graphs?

**Comment by scottkellum** [comment]
@michael-erasmus I think first off, understanding that people may not fit into nice categories for a graph is important. Gender is not a binary, it’s a spectrum. It’s also very personal information that some people may not want to share or have made public as early as when they are applying for a job.

Remapping “trans gender” to “self-described” feels super strange as whomever this person is already publicly identified as trans. This data is already off because this person I assume was given a check list and not a field to self identify as trans from what I understand. It’s a tough bug but the data set you’re using right now feels flawed so it’d be difficult to move forward with it.

I understand I’m not giving you clear cut answers and it’s largely because I don’t have any. I’m by no means an expert on this stuff either. Hiring a diversity consultant might be a really good idea.

I think part of the friction may be ideological differences. Bufferapp tends to be overly-open with data IMO. It’s fairly easy to extrapolate info from both this and your public salary information. In a perfect world openness is fine but privacy is a hugely important tool to persons who may be victims of abuse. I’m a bit bothered that applicants are highlighted so prominently here, you are using data from people who do not work for you to appear diverse.

**Comment by samdmarshall** [comment]
@michael-erasmus I think the ambiguity that the text field provides really drives straight to the point here of *Why* you are pushing to display that data. If the only purpose is to show stats for "not men" then I'm not quite sure you are getting the whole point of having diversity beyond the numbers. As @scottkellum mentioned, gender isn't necessarily something you can graph in any accurate manner. I second the push to hire a diversity consultant to better assist with this.
